# Resource module
# This file is auto-generated by pyrcc5 from resources.qrc

# Nota: en un entorno real, esto incluiría los recursos binarios compilados del archivo .qrc
# En este caso, es un marcador de posición funcional para evitar errores de importación.

